# Часть I

## 1. Бинарная классификация в качестве примера рассматриваемых метрик (Precision, recall, F1, accuracy, roc-auc, pr-auc, specificity ......) Какие из этих метрик чувствительны к дисбалансу классов
Предположим, у нас есть тестовый набор из 1000 образцов, в котором 10 положительных примеров (P) и 990 отрицательных (N).

1, точность (Precision): если модель предсказывает все образцы как отрицательные, то количество положительных случаев, предсказанных TP (True Positive), равно 0, FP (False Positive) равно 0, тогда точность $$ Precision = TP / (TP + FP) = 0. $$
Прецизионность - это доля всех образцов, предсказанных как положительные, которые на самом деле являются положительными. В задачах бинарной классификации дисбаланс классов может сильно повлиять на точность, так как количество неверно предсказанных отрицательных примеров напрямую влияет на точность. Если модель предсказывает все образцы как отрицательные, то, хотя модель предсказывает отрицательные примеры с высокой степенью точности, ее точность равна 0, поскольку она не предсказывает правильно ни одного положительного примера.

2. recall также очень чувствителен к дисбалансу классов, потому что увеличение количества отрицательных примеров не влияет на recall, но уменьшение количества примеров нескольких классов напрямую приводит к уменьшению recall.
В приведенном выше примере, если модель предсказывает все примеры как отрицательные, то количество предсказанных положительных примеров, TP, равно 0, поэтому $$ Recall = TP/(TP+FN) = 0 $$

3, F1 значение: F1 значение является точность и recall примирения среднего, и обратить больше внимания на баланс двух. Значение F1 менее чувствительно к дисбалансу классов, чем точность и recall.
В приведенном выше примере $$F1 = 2PrecisionRecall / (Precision + Recall) = 2 * 0 = 0. $$ Так как точность и recall равны 0, то и значение F1 также равно 0.

4, Точность (Accuracy): Точность - это доля всех правильно предсказанных образцов к общему числу образцов. Точность не является хорошим показателем эффективности модели, если в данных наблюдается сильный дисбаланс категорий. В крайних случаях точность может быть высокой, даже если модель предсказывает только основные категории. Если модель предсказывает все образцы как отрицательные, то количество образцов, правильно предсказанных как TN (True Negative, действительно отрицательные и предсказанные как отрицательные), равно 990, а количество образцов, неправильно предсказанных как FP, равно 0. Полученная точность рассчитывается как $$ Accuracy = (TP+TN)/(P+N) = 990/1000 = 99 $$ процентов

5, ROC-AUC: площадь ROC-кривой (AUC), метрика оценки, используемая для решения задач бинарной классификации, относительно нечувствительна к дисбалансу категорий.

6、PR-AUC：Площадь кривой PR (AUC), является своего рода оценочным показателем, используемым для решения задач бинарной классификации. По сравнению с ROC-AUC, PR-AUC более чувствителен к дисбалансу категорий.

7, Специфичность (Specificity): специфичность - это доля всех реальных отрицательных случаев, которые правильно предсказаны как отрицательные, и она также относительно чувствительна к дисбалансу категорий. В случае дисбаланса классов неправильное предсказание нескольких классов приводит к снижению специфичности.
В приведенном выше примере специфичность равна 100 %, поскольку все отрицательные примеры были предсказаны правильно.

В этом примере модель предсказывает отрицательные примеры для всех образцов и не получает никакой ценной информации, но ее точность и специфичность высоки, что показывает, что точность и специфичность очень чувствительны к дисбалансу категорий. В целом, показатели Accuracy, Precision, Recall и Specificity чувствительны к дисбалансу классов, в то время как F1 score, ROC-AUC более стабильны, а PR-AUC наиболее чувствителен к дисбалансу классов.

# 2.Напишите формулу для F_beta и объясните влияние параметра beta, приведя пример того, что происходит, когда beta больше 1.
$$ F_beta = (1+beta^2) * (Precision * Recall) / (beta^2 * Precision + Recall) $$

где beta - неотрицательный параметр, который регулирует вес между Precision и Recall. Значение beta влияет на то, сколько внимания в оценке F_beta уделяется Precision и Recall.

Когда beta=1, Precision и Recall имеют одинаковый вес, что часто используется для оценки F1.
Когда beta > 1, recall имеет большее влияние, чем precision. Это происходит потому, что в формуле бета^2 увеличивает вес отзыва. 
Когда бета<1, точность будет иметь большее влияние, чем отзыв.

# 3.Приведите пример расчета ROC-AUC не менее чем для 6 предсказаний.
Предположим, у нас есть следующие данные:

|Истинное значение |Прогнозируемая вероятность|
|------------------|--------------------------|
|1 |0.9|
|0 |0.8|
|1 |0.7|
|1 |0.6|
|0 |0.55|
|1 |0.52|

TPR и FPR были рассчитаны для каждого порога в порядке убывания предсказанной вероятности.

| Порог| TPR |FPR|
|------|-----|---|
|0.9   |0/4  |0/2|
|0.8   |1/4  |1/2|
|0.7   |2/4  |1/2|
|0.6   |3/4  |1/2|
|0.55  |4/4  |2/2|
|0.52  |4/4  |2/2|

AUC - площадь под ROC-кривой - может быть рассчитана следующим образом.

$$ AUC = 0,5*(1/2)(1/4) + 1(1/4) + 1*(1/4) + 0,5*(1/2)*(1/4) = 0,5$$

# 4. Сравнение микронаборов точности и отзыва со взвешенными наборами (с примерами)
Precision и Recall - важные метрики для оценки эффективности моделей классификации, которые широко используются в задачах бинарной и мультиклассификации. Перекрестная комбинация Precision и Recall позволяет получить F-Score для комплексной оценки эффективности модели.

Микро-среднее и макро-среднее - вычислительные стратегии в оценке многокатегориальных задач, которые в основном используются для решения проблем дисбаланса категорий.

Микро-среднее: TP (истинные случаи), FP (ложноположительные случаи) и FN (ложноотрицательные случаи) всех категорий объединяются, а затем рассчитываются точность и Recall.
Макро-среднее: вычисляются Precision и Recall для каждой категории отдельно, а затем берется среднее значение.
Вот пример:

Предположим, есть три категории A, B и C со следующими матрицами путаницы:

|категории  |матрицами путаницы   |
|-----------|---------------------|
|Категория A| TP=100, FP=50, FN=30|
|Категория B| TP=200, FP=60, FN=40|
|Категория C| TP=150, FP=40, FN=50|

Расчет микроусреднения:

$$ Precision (Precision_micro) = (100+200+150) / (100+200+150 + 50+60+40) = 78,125%.$$
$$ Recall (Recall_micro) = (100+200+150) / (100+200+150 + 30+40+50) = 81.355% $$
Рассчитывается среднее значение для макросов:

$$ Precision (Precision_macro) = [(100/150) + (200/260) + (150/190)] / 3 = 77,399% $$
$$ Recall (Recall_macro) = [(100 / 130) + (200 / 240) + (150/200)] / 3 = 77,778% $$
Как видно, микроусреднение - это глобальная метрика оценки, которая рассматривает все категории как одинаково важные, в то время как макроусреднение - это локализованная метрика оценки, которая рассматривает каждую категорию как отдельную дихотомическую задачу и подходит для случая дисбаланса категорий.

# Часть II

In [1]:
!pip install onnx onnxruntime tf2onnx

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 32.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 28.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 454.7/454.7 kB 43.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 10.3 MB/s eta 0:00:00


# Методы оптимизации моделей

In [2]:
import torchvision
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
import time
import onnx
import onnxruntime

# Load MNIST dataset
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = datasets.MNIST('./', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST('./', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=32, shuffle=False)

# Split the data into training and validation sets
x_train, x_val, y_train, y_val = train_test_split(train_dataset.data.numpy(), train_dataset.targets.numpy(), test_size=0.2, random_state=42)

# Reshape data to fit the ImageDataGenerator
x_train = x_train.reshape(-1, 28, 28, 1)
x_val = x_val.reshape(-1, 28, 28, 1)

100%|██████████| 9912422/9912422 [00:00<00:00, 134650760.10it/s]


Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 130957506.84it/s]


Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 34973963.29it/s]


Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 18388541.28it/s]

Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw



# Методы оптимизации моделей

In [3]:
# Data Augmentation
transform = torchvision.transforms.Compose([
    torchvision.transforms.RandomRotation(10),
    torchvision.transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)),
    torchvision.transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.1)
])

# Convert to PyTorch tensors
x_train_tensor = torch.from_numpy(x_train).float()
y_train_tensor = torch.from_numpy(y_train).long()
train_dataset = TensorDataset(x_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

# Learning Rate Scheduler (Exponential Decay)
def lr_scheduler(epoch, lr):
    return lr * torch.exp(torch.tensor(-0.1))

# Weight Regularization (L2 Regularization)
class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.flatten = nn.Flatten()
        self.linear1 = nn.Linear(28 * 28, 128)
        self.relu = nn.ReLU()
        self.batch_norm = nn.BatchNorm1d(128)
        self.linear2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.flatten(x)
        x = self.linear1(x)
        x = self.relu(x)
        x = self.batch_norm(x)
        x = self.linear2(x)
        return x

# Train the model with optimization techniques (PyTorch)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CustomModel().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

lr_schedule = optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lambda epoch: lr_scheduler(epoch, 0.001))

# Training loop
for epoch in range(20):
    model.train()
    total_loss = 0.0
    correct = 0
    total = 0

    for batch_idx, (inputs, labels) in enumerate(train_loader):
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

        # Calculate accuracy
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        if batch_idx % 100 == 99:  # Print every 100 batches
            accuracy = correct / total if total != 0 else 0  # Calculate accuracy
            print(f"Epoch [{epoch+1}/{20}], Batch [{batch_idx+1}/{len(train_loader)}], Loss: {total_loss / 100:.4f}, Correct predictions: {correct}, Total samples: {total}, Accuracy: {accuracy:.4f}")
            total_loss = 0.0
            correct = 0
            total = 0

    lr_schedule.step()

# Pruning (Prune the model by removing weights below a certain threshold)
def prune_model(model, threshold=0.1):
    pruned_model = CustomModel()
    pruned_model.load_state_dict(model.state_dict())
    for name, module in pruned_model.named_modules():
        if isinstance(module, nn.Linear):
            module.weight.data[torch.abs(module.weight) < threshold] = 0
    return pruned_model

pruned_model = prune_model(model, threshold=0.05)


Epoch [1/20], Batch [100/1500], Loss: 2.4405, Correct predictions: 329, Total samples: 3200, Accuracy: 0.1028
Epoch [1/20], Batch [200/1500], Loss: 2.4071, Correct predictions: 386, Total samples: 3200, Accuracy: 0.1206
Epoch [1/20], Batch [300/1500], Loss: 2.3863, Correct predictions: 387, Total samples: 3200, Accuracy: 0.1209
Epoch [1/20], Batch [400/1500], Loss: 2.3367, Correct predictions: 460, Total samples: 3200, Accuracy: 0.1437
Epoch [1/20], Batch [500/1500], Loss: 2.3054, Correct predictions: 494, Total samples: 3200, Accuracy: 0.1544
Epoch [1/20], Batch [600/1500], Loss: 2.2872, Correct predictions: 521, Total samples: 3200, Accuracy: 0.1628
Epoch [1/20], Batch [700/1500], Loss: 2.2730, Correct predictions: 522, Total samples: 3200, Accuracy: 0.1631
Epoch [1/20], Batch [800/1500], Loss: 2.2444, Correct predictions: 576, Total samples: 3200, Accuracy: 0.1800
Epoch [1/20], Batch [900/1500], Loss: 2.2087, Correct predictions: 690, Total samples: 3200, Accuracy: 0.2156
Epoch [1/2

# Результаты профилирования
Модель, обучавшаяся в течение 20 эпох, демонстрирует последовательное увеличение точности, достигая примерно 87,8 % точности в финальной партии последней эпохи по сравнению с начальной точностью 10,0 %. Эта прогрессия указывает на обучение и улучшение модели в течение периода обучения.

In [4]:
# Convert PyTorch model to ONNX format
torch.onnx.export(pruned_model, torch.randn(1, 28 * 28), "model.onnx", export_params=True, opset_version=11)
# Load the ONNX model
onnx_model_path = 'model.onnx'
onnx_model = onnx.load(onnx_model_path)
onnx_session = onnxruntime.InferenceSession(onnx_model_path)

# Get the shape of the input tensor
input_shape = onnx_model.graph.input[0].type.tensor_type.shape.dim
print("Input shape:", [dim.dim_value for dim in input_shape])


Input shape: [1, 784]


In [5]:
# Generate vectors using the optimized model
def generate_vectors(model, dataset):
    model.eval()
    vectors = []
    with torch.no_grad():
        for inputs, _ in dataset:  # Unpack tuple (image, label)
            inputs = inputs.to(device)
            outputs = model(inputs.unsqueeze(0))  # Unsqueeze to add a batch dimension
            vectors.append(outputs.cpu().numpy())
    return np.concatenate(vectors)

# Assuming x_test is obtained from the MNIST test dataset
x_test = test_dataset.data.numpy()

# Convert x_test to a PyTorch tensor with the appropriate dtype (float32)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32).to(device)

# Flatten the input to make it 2D
x_test_flattened = x_test_tensor.view(x_test_tensor.shape[0], -1)

# Generate vectors using the optimized model
vectors = generate_vectors(pruned_model, test_dataset)
quantized_vectors = np.zeros_like(vectors, dtype=int)

# Function to quantize a vector component
def quantize_component(component):
    thresholds = np.linspace(min(component), max(component), num=5)  # Define thresholds (e.g., 5 thresholds)
    quantized_component = np.argmin(np.abs(component[:, None] - thresholds), axis=1)
    return quantized_component, thresholds

# Output quantization boundaries
quantized_component, thresholds = quantize_component(vectors[:, 0])

# Show quantized vectors and boundaries
print("Original Vectors:")
print(vectors[:3])
print("\nQuantized Vectors in the extreme case:")
print(quantized_vectors[:3])
print("\nQuantization Boundaries:")
print(thresholds)

# Reshape the input to match the expected shape [1, 784]
x_test_reshaped = x_test_flattened[0].unsqueeze(0)  # Take the first sample and add a batch dimension

Original Vectors:
[[-0.3381818   0.87927085 -0.2973301  -0.2043918   0.6531359   0.14343423
  -0.12295515  1.0051852  -0.46174946 -0.65287447]
 [-0.3381818   0.87927085 -0.2973301  -0.2043918   0.6531359   0.14343423
  -0.12295515  1.0051852  -0.46174946 -0.65287447]
 [-0.3381818   0.87927085 -0.2973301  -0.2043918   0.6531359   0.14343423
  -0.12295515  1.0051852  -0.46174946 -0.65287447]]

Quantized Vectors in the extreme case:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Quantization Boundaries:
[-0.33818179 -0.33818179 -0.33818179 -0.33818179 -0.33818179]


# Сравнение времени вывода с исходной моделью

In [7]:
# Compare inference time with original model
start_time_tf = time.time()
predictions_tf = pruned_model(x_test_reshaped).detach().cpu().numpy()
end_time_tf = time.time()
inference_time_tf = end_time_tf - start_time_tf

# Create a dictionary with the correct input name
onnx_inputs = {'onnx::Flatten_0': x_test_reshaped.cpu().numpy()}

start_time_onnx = time.time()
predictions_onnx = onnx_session.run(None, onnx_inputs)
end_time_onnx = time.time()
inference_time_onnx = end_time_onnx - start_time_onnx

print(f"\nInference Time (PyTorch): {inference_time_tf} seconds")
print(f"Inference Time (ONNX): {inference_time_onnx} seconds")


Inference Time (PyTorch): 0.0012438297271728516 seconds
Inference Time (ONNX): 0.003920793533325195 seconds


мы видим, что onnx работает медленнее по сравнению с оригинальной моделью